algoritmo "soma dos numeros guanabara"
var
 numero1,numero2,s: inteiro //da para declarar 2 variaveis no mesmo espaco
inicio
 escreval("digite dois numeros que vou mostrar a soma entre eles ")
 escreva ("digite o primeiro numero: ")
 leia (numero1)
 escreva ("digite o segundo numero: ")
 leia(numero2)
 s <- numero1 + numero2 //mais simples ja atribui a soma a uma variavel
 Escreval("o resultado eh igual a",s)
fimalgoritmo
